//
// CartoesidCartaosaldoSaldo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CartoesidCartaosaldoSaldo: JSONEncodable {
    /** Valor monetário  a ser creditado (valor positivo) ou debitado (valor negativo) na conta do cartão. */
    public var valor: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["valor"] = self.valor
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
