//
// NovoCartaoPortadorContato.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class NovoCartaoPortadorContato: JSONEncodable {
    /** Endereço  de email do portador do cartão. */
    public var email: String?
    /** Telefone Residencial no formato: 01199999999. Não deve conter números sequenciais ou repetidos */
    public var telResidencial: String?
    /** Telefone Celular no formato: 011999999999. Não deve conter números sequenciais ou repetidos */
    public var telCelular: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["email"] = self.email
        nillableDictionary["telResidencial"] = self.telResidencial
        nillableDictionary["telCelular"] = self.telCelular
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
