//
// Portador.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Portador: JSONEncodable {
    /** Nome do portador do cartão. */
    public var nome: String?
    /** Endereço  de e-mail do portador do cartão. */
    public var email: String?
    /** Numero do telefone celular do portador do cartão. */
    public var celular: String?
    public var endereco: InlineResponse2002PortadorEndereco?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["nome"] = self.nome
        nillableDictionary["email"] = self.email
        nillableDictionary["celular"] = self.celular
        nillableDictionary["endereco"] = self.endereco?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
