//
// SetCardStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SetCardStatus: JSONEncodable {
    public enum Status: String { 
        case Bloqueado = "bloqueado"
        case Desbloqueado = "desbloqueado"
    }
    /** Novo status do cartão para o qual se deseja alterar */
    public var status: Status?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["status"] = self.status?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
