//
// SetPagamento.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SetPagamento: JSONEncodable {
    /** número identificador referente ao proxy do cartão. */
    public var idCartao: String?
    /** Senha do cartão. */
    public var senha: String?
    /** Código de pagamento identificado no documento (boleto). */
    public var codigoBarras: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["idCartao"] = self.idCartao
        nillableDictionary["senha"] = self.senha
        nillableDictionary["codigoBarras"] = self.codigoBarras
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
