//
// TransferenciaCadastroBenificiario.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TransferenciaCadastroBenificiario: JSONEncodable {
    public var beneficiario: TransferenciascadastrosBeneficiario?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["beneficiario"] = self.beneficiario?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
