//
// CartoesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class CartoesAPI: APIBase {
    /**
     Consulta o extrato do cartão
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 
     - parameter dataInicial: (query) Data inicial para a consulta (YYYY-MM-DD). 
     - parameter dataFinal: (query) Data final para a consulta (YYYY-MM-DD).. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func cartoesIdCartaoExtratoGet(clientId clientId: String, accessToken: String, idCartao: String, dataInicial: NSDate, dataFinal: NSDate, completion: ((data: InlineResponse2001?, error: ErrorType?) -> Void)) {
        cartoesIdCartaoExtratoGetWithRequestBuilder(clientId: clientId, accessToken: accessToken, idCartao: idCartao, dataInicial: dataInicial, dataFinal: dataFinal).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Consulta o extrato do cartão
     - GET /cartoes/{idCartao}/extrato
     - <p>Permite a consulta dos movimentos por período de um determinado cartão. A janela máxima de observação é de 30 dias, e as datas inicial e final de observação pode ser configuradas, conforme necessidade.</p>
     - examples: [{contentType=application/json, example={
  "extrato" : [ {
    "tipo" : "CARGA",
    "estabelecimento" : "Super Mercado do João",
    "valor" : 100.1,
    "dataHora" : "12/12/2012 12:12:12"
  } ]
}}]
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 
     - parameter dataInicial: (query) Data inicial para a consulta (YYYY-MM-DD). 
     - parameter dataFinal: (query) Data final para a consulta (YYYY-MM-DD).. 

     - returns: RequestBuilder<InlineResponse2001> 
     */
    public class func cartoesIdCartaoExtratoGetWithRequestBuilder(clientId clientId: String, accessToken: String, idCartao: String, dataInicial: NSDate, dataFinal: NSDate) -> RequestBuilder<InlineResponse2001> {
        var path = "/cartoes/{idCartao}/extrato"
        path = path.stringByReplacingOccurrencesOfString("{idCartao}", withString: "\(idCartao)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "dataInicial": dataInicial.encodeToJSON(),
            "dataFinal": dataFinal.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2001>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**
     Consuta informações do portador do cartão
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func cartoesIdCartaoPortadorGet(clientId clientId: String, accessToken: String, idCartao: String, completion: ((data: InlineResponse2002?, error: ErrorType?) -> Void)) {
        cartoesIdCartaoPortadorGetWithRequestBuilder(clientId: clientId, accessToken: accessToken, idCartao: idCartao).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Consuta informações do portador do cartão
     - GET /cartoes/{idCartao}/portador
     - <p>Permite a consulta de informações cadastrais de um determinado portador de cartão.</p>
     - examples: [{contentType=application/json, example={
  "portador" : {
    "endereco" : {
      "cidade" : "Pinheiros",
      "estado" : "SP",
      "codigoPostal" : "05425070",
      "logradouro" : "Av. das Nações Unidas"
    },
    "celular" : "011998767654",
    "nome" : "João da Silva",
    "email" : "joao.siva@mail.com"
  }
}}]
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 

     - returns: RequestBuilder<InlineResponse2002> 
     */
    public class func cartoesIdCartaoPortadorGetWithRequestBuilder(clientId clientId: String, accessToken: String, idCartao: String) -> RequestBuilder<InlineResponse2002> {
        var path = "/cartoes/{idCartao}/portador"
        path = path.stringByReplacingOccurrencesOfString("{idCartao}", withString: "\(idCartao)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2002>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     Consulta o saldo do cartão
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func cartoesIdCartaoSaldoGet(clientId clientId: String, accessToken: String, idCartao: String, completion: ((data: InlineResponse200?, error: ErrorType?) -> Void)) {
        cartoesIdCartaoSaldoGetWithRequestBuilder(clientId: clientId, accessToken: accessToken, idCartao: idCartao).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Consulta o saldo do cartão
     - GET /cartoes/{idCartao}/saldo
     - <p>Permite a consulta do saldo disponível de um determinado cartão.</p>
     - examples: [{contentType=application/json, example={
  "saldo" : {
    "valor" : 10.1
  }
}}]
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 

     - returns: RequestBuilder<InlineResponse200> 
     */
    public class func cartoesIdCartaoSaldoGetWithRequestBuilder(clientId clientId: String, accessToken: String, idCartao: String) -> RequestBuilder<InlineResponse200> {
        var path = "/cartoes/{idCartao}/saldo"
        path = path.stringByReplacingOccurrencesOfString("{idCartao}", withString: "\(idCartao)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse200>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     Credita ou debita valor da conta de um cartão.
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 
     - parameter saldo: (body) Objeto de requisição 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func cartoesIdCartaoSaldoPut(clientId clientId: String, accessToken: String, idCartao: String, saldo: Saldo, completion: ((error: ErrorType?) -> Void)) {
        cartoesIdCartaoSaldoPutWithRequestBuilder(clientId: clientId, accessToken: accessToken, idCartao: idCartao, saldo: saldo).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Credita ou debita valor da conta de um cartão.
     - PUT /cartoes/{idCartao}/saldo
     - <p>Permite creditar ou debitar um valor especifico em um determinado cartão.</p><br/><p class='obs obs-danger'>Este recurso deve ser utilizado somente pelo reseller e quando o credito do cartão for de responsabilidade e propriedade do Reseller.</p>
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 
     - parameter saldo: (body) Objeto de requisição 

     - returns: RequestBuilder<Void> 
     */
    public class func cartoesIdCartaoSaldoPutWithRequestBuilder(clientId clientId: String, accessToken: String, idCartao: String, saldo: Saldo) -> RequestBuilder<Void> {
        var path = "/cartoes/{idCartao}/saldo"
        path = path.stringByReplacingOccurrencesOfString("{idCartao}", withString: "\(idCartao)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = saldo.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     Consulta o status do cartão
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func cartoesIdCartaoStatusGet(clientId clientId: String, accessToken: String, idCartao: String, completion: ((data: InlineResponse2003?, error: ErrorType?) -> Void)) {
        cartoesIdCartaoStatusGetWithRequestBuilder(clientId: clientId, accessToken: accessToken, idCartao: idCartao).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Consulta o status do cartão
     - GET /cartoes/{idCartao}/status
     - <p>Permite a consulta do status de um determinado cartão. O status do cartão nos permite saber se o cartão esta ativo, bloqueado, desbloqueado ou cancelado.</p>
     - examples: [{contentType=application/json, example={
  "status" : "bloqueado"
}}]
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 

     - returns: RequestBuilder<InlineResponse2003> 
     */
    public class func cartoesIdCartaoStatusGetWithRequestBuilder(clientId clientId: String, accessToken: String, idCartao: String) -> RequestBuilder<InlineResponse2003> {
        var path = "/cartoes/{idCartao}/status"
        path = path.stringByReplacingOccurrencesOfString("{idCartao}", withString: "\(idCartao)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2003>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     Altera status do cartão
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 
     - parameter status: (body) Objeto de requisição 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func cartoesIdCartaoStatusPut(clientId clientId: String, accessToken: String, idCartao: String, status: Status, completion: ((error: ErrorType?) -> Void)) {
        cartoesIdCartaoStatusPutWithRequestBuilder(clientId: clientId, accessToken: accessToken, idCartao: idCartao, status: status).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Altera status do cartão
     - PUT /cartoes/{idCartao}/status
     - <p>Permite o bloqueio e desbloqueio de um determinado cartão.</p>
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter idCartao: (path) Número identificador referente ao proxy localizado no verso do cartão. 
     - parameter status: (body) Objeto de requisição 

     - returns: RequestBuilder<Void> 
     */
    public class func cartoesIdCartaoStatusPutWithRequestBuilder(clientId clientId: String, accessToken: String, idCartao: String, status: Status) -> RequestBuilder<Void> {
        var path = "/cartoes/{idCartao}/status"
        path = path.stringByReplacingOccurrencesOfString("{idCartao}", withString: "\(idCartao)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = status.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     Associa um número de proxy de cartão a um portador.
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter cartao: (body) Objeto de requisição 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func cartoesPost(clientId clientId: String, accessToken: String, cartao: Cartao, completion: ((error: ErrorType?) -> Void)) {
        cartoesPostWithRequestBuilder(clientId: clientId, accessToken: accessToken, cartao: cartao).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Associa um número de proxy de cartão a um portador.
     - POST /cartoes
     - <p>Operação responsável por associar um número proxy de cartão a um portador.</p><br/> <p>Esse processo de liberação é assíncrono.</p> 
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter cartao: (body) Objeto de requisição 

     - returns: RequestBuilder<Void> 
     */
    public class func cartoesPostWithRequestBuilder(clientId clientId: String, accessToken: String, cartao: Cartao) -> RequestBuilder<Void> {
        let path = "/cartoes"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = cartao.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

}
