//
// PagamentosAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class PagamentosAPI: APIBase {
    /**
     Pagamento de boletos.
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter boleto: (body) Objeto de requisição 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func pagamentosPost(clientId clientId: String, accessToken: String, boleto: Boleto, completion: ((error: ErrorType?) -> Void)) {
        pagamentosPostWithRequestBuilder(clientId: clientId, accessToken: accessToken, boleto: boleto).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Pagamento de boletos.
     - POST /pagamentos
     - <p>Permite o pagamento de boletos.</p>
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter boleto: (body) Objeto de requisição 

     - returns: RequestBuilder<Void> 
     */
    public class func pagamentosPostWithRequestBuilder(clientId clientId: String, accessToken: String, boleto: Boleto) -> RequestBuilder<Void> {
        let path = "/pagamentos"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = boleto.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

}
