//
// TransferenciasAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class TransferenciasAPI: APIBase {
    /**
     Cadastro de beneficiário para Transferencia
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter beneficiario: (body) Objeto de requisição 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func transferenciasCadastrosPost(clientId clientId: String, accessToken: String, beneficiario: Beneficiario, completion: ((error: ErrorType?) -> Void)) {
        transferenciasCadastrosPostWithRequestBuilder(clientId: clientId, accessToken: accessToken, beneficiario: beneficiario).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Cadastro de beneficiário para Transferencia
     - POST /transferencias/cadastros
     - <p>Permite o cadastro de beneficiário para uma transferencia.</p>
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter beneficiario: (body) Objeto de requisição 

     - returns: RequestBuilder<Void> 
     */
    public class func transferenciasCadastrosPostWithRequestBuilder(clientId clientId: String, accessToken: String, beneficiario: Beneficiario) -> RequestBuilder<Void> {
        let path = "/transferencias/cadastros"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = beneficiario.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     Transferência de valores entre contas
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter transferencia: (body) Objeto de requisição 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func transferenciasPost(clientId clientId: String, accessToken: String, transferencia: Transferencia, completion: ((error: ErrorType?) -> Void)) {
        transferenciasPostWithRequestBuilder(clientId: clientId, accessToken: accessToken, transferencia: transferencia).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Transferência de valores entre contas
     - POST /transferencias
     - <p>Permite a transferência de valor entre dois cartões pré cadastrados.</p>
     
     - parameter clientId: (header) Identificador do cliente utilizado na autenticação. 
     - parameter accessToken: (header) Token de acesso utilizado na autenticação. 
     - parameter transferencia: (body) Objeto de requisição 

     - returns: RequestBuilder<Void> 
     */
    public class func transferenciasPostWithRequestBuilder(clientId clientId: String, accessToken: String, transferencia: Transferencia) -> RequestBuilder<Void> {
        let path = "/transferencias"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = transferencia.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

}
